---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Phone
no_index:
  directory:
    - t
    - inc
requires:
  DBM::Deep: 2.0008
  Digest::MD5: 0
  Scalar::Util: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/DrHyde/perl-modules-Number-Phone/issues
  repository: https://github.com/DrHyde/perl-modules-Number-Phone
version: 3.0004
