# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Number-Phone
version:      1.51
version_from: 
installdirs:  site
requires:
    DBM::Deep:                     0.97
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
